### ISSUE TITLE
genQuery return at most 100 records

### ISSUE THREAD

**Issue by km4rcus** [DICE-UNC/irods-rest#44]
When I use genQuery, the response contains at most 100 records in the result set.
Should I pass any parameter to get the whole record set?

**Comment by lstillwe** [comment]
Use the count parameter it is set to a default of 100.
[RENCI]<http://www.renci.org>

Lisa Stillwell
Research Software Developer/GIS Specialist



On Feb 25, 2016, at 10:02 AM, Marco Mancini <notifications@github.com<mailto:notifications@github.com>> wrote:


When I use genQuery, the response contains at most 100 records in the result set.
Should I pass any parameter to get the whole record set?

**Comment by km4rcus** [comment]
Ok thanks! I added count and it works. So in order to get all the records, should i just set count to a sufficient "big" number?

**Comment by michael-conway** [comment]
I bumped up the count (bad to have magic numbers, but we'll address this and move it to config in the next version).
