### ISSUE TITLE
STANDARD auth option is now hardcoded

### ISSUE THREAD

**Issue by mpasserini** [DICE-UNC/irods-rest#45]
It seems that the following file does not read irods-ext/irods-rest.properties anymore for the authentication type (PAM/STANDARD), I think this is an issue.
https://github.com/DICE-UNC/irods-rest/blob/master/src/main/resources/jargon-beans.xml#L41

**Comment by JustinKyleJames** [comment]
Yes, this was a mistake.  I will fix this as well as cors.allow and default.storage.resource.

**Comment by JustinKyleJames** [comment]
I updated this.  It now has the correct settings without hardcoded values.
