### ISSUE TITLE
Deleting ticket produces no feedback if it doesn't exist

### ISSUE THREAD

**Issue by muhrin** [DICE-UNC/irods-rest#47]
Deleting a non-existent ticket: e.g.

`curl -X DELETE http://***:8080/irods-rest/rest/ticket/11a9wD9TGRTnnlm`

Gives no indication that the ticket doesn't exist.  Perhaps it could return 'Not found'?

I'm not sure what is normal for a REST interface but some feedback would be useful.

**Comment by JustinKyleJames** [comment]
This is true.  This was designed to work just as deleting a data object which also doesn't produce an error if the data object does not exist.  Mike is of the belief that this is how the REST service should be idempotent and return 204 in either case as long as the ticket is not there once completed.

I don't have a strong opinion on this either way but I am hesitant to make this work differently than other parts of the rest interface.   We should probably discuss further.

**Comment by muhrin** [comment]
I get the idempotence issue and I completely agree that DELETE should be this way.  The only only point of debate is if this should apply to the response or simply to representation (i.e. the iRODS state).  It seems that RFC 2616 [1] is not clear on this and there is certainly debate out there about which way around it should be e.g. [2].  My personal view is that given that there is ambiguity in the spec. of the two options it's preferable to choose the more useful one which tells the user that the file doesn't exist to be deleted.

I also agree that there shouldn't be an exception for tickets.  Either it's change for both or neither.

[1] http://www.ietf.org/rfc/rfc2616.txt
[2] http://leedavis81.github.io/is-a-http-delete-requests-idempotent/

**Comment by michael-conway** [comment]
I'm going to defer this for now, we'll be re-approaching REST with the consortium and we'll see what consensus emerges.  Currently idempotency in REST here includes in response status codes.
