### ISSUE TITLE
Downloaded files include parameters in name

### ISSUE THREAD

**Issue by mpasserini** [DICE-UNC/irods-rest#48]
Hi,

If I do something like this:
###### 

> iticket create read /myzone/home/me/test.txt
> ticket:TiNnx2HICG7YE9t
> wget --no-check-certificate http://myurl/irods-rest/rest/fileContents/myzone/home/me/test.txt?ticket=TiNnx2HICG7YE9t
> --2016-03-29 12:02:56--  http://myurl/irods-rest/rest/fileContents/myzone/home/me/test.txt?ticket=TiNnx2HICG7YE9t
> Resolving myurl... 148.187.25.140
> Connecting to myurl|148.187.25.140|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 8 [application/octet-stream]
> Saving to: `test.txt?ticket=TiNnx2HICG7YE9t'

100%[==========================================================================================================>] 8           --.-K/s   in 0s     

2016-03-29 12:02:57 (1.22 MB/s) - `test.txt?ticket=TiNnx2HICG7YE9t' saved [8/8]
###### 

As you can see, the downloaded file is called: test.txt?ticket=TiNnx2HICG7YE9t .I would like the file to be called just test.txt. It this a bug in the REST API or is there some configuration I could do to prevent this type of formatting which includes GET parameters in the file name?

Thanks in advance.

**Comment by muhrin** [comment]
Indeed, this is affecting us.  From my understanding the 'standard' way of achieving this is to put in the server-side header:

Content-disposition "attachment; filename=[the filename]"

e.g. http://stackoverflow.com/questions/9309102/setting-a-filename-inside-the-header-with-htaccess

Maybe the iRODS fileContents GET request could have this as an optional parameter or just have a server-side setting to switch to just returning the filename (sans ticket id).

**Comment by mpasserini** [comment]
I guess the problem is around this line of code?
https://github.com/DICE-UNC/irods-rest/blob/3a0aaee0aa454a5e808da3ad0b5991252e705281/src/main/java/org/irods/jargon/rest/commands/dataobject/FileContentsService.java#L259
I don't have time to debug in these days, I just leave this link here in case someone has a quick idea on how to fix it.

**Comment by JustinKyleJames** [comment]
If you do the wget with the --content-disposition flag set then it will write the correct filename.  I believe this forces wget to look at the content-disposition header to determine the filename to use.

```
wget --no-check-certificate --content-disposition http://justin:justin@localhost:8080/irods-rest/rest/fileContents/tempZone/home/rods/test.txt?ticket=4Rc15438h5RR2cf
--2016-04-12 12:57:34--  http://justin:*password*@localhost:8080/irods-rest/rest/fileContents/tempZone/home/rods/test.txt?ticket=4Rc15438h5RR2cf
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 401 Unauthorized
Reusing existing connection to [localhost]:8080.
HTTP request sent, awaiting response... 200 OK
Length: 149 [application/octet-stream]
Saving to: ‘test.txt’

100%[======================================>] 149         --.-K/s   in 0s      

2016-04-12 12:57:35 (27.2 MB/s) - ‘test.txt’ saved [149/149]
```

**Comment by muhrin** [comment]
Thanks a lot Justin, that certainly makes things better.

Unfortunately the response header Content-Disposition contains the full
path and not just the basename which is what we're after.  I believe this
is what most users would expect, but I may be wrong.  In case here's a
patch to do just that:

diff --git
a/src/main/java/org/irods/jargon/rest/commands/dataobject/FileContentsService.java
b/src/main/java/org/irod
index c44f3d5..d557f5a 100644
---
a/src/main/java/org/irods/jargon/rest/commands/dataobject/FileContentsService.java
+++
b/src/main/java/org/irods/jargon/rest/commands/dataobject/FileContentsService.java
@@ -257,7 +257,7 @@ public class FileContentsService extends
AbstractIrodsService {
                        response.setContentType("application/octet-stream");
                        response.setContentLength(contentLength);
                        response.setHeader("Content-disposition",
"attachment; filename=\""
-                                       + decodedPathString + "\"");
+                                       + irodsFile.getName() + "\"");

                        // test hack of origin for cors download


If you'd rather not have this as the default behaviour is there somewhere
we could put it as an optional setting?

Thanks again,
-Martin

**Comment by michael-conway** [comment]
That's a great patch.  I'll merge this in.  I'm in the middle of 
building some javascript-based integration tests to clear up some of the 
ticket issues and then we'll get a release

MC
