### ISSUE TITLE
irods-rest.properties example

### ISSUE THREAD

**Issue by kript** [DICE-UNC/irods-rest#56]
Hi folks,

Is it possible to have an example added to the documentation? This would show me, as a tomcat/Java newbie, how its supposed to be configured. I'm specifically interested in the 
`web.interface.url=` line in the config; should this be

`web.interface.url=http://localhost/irods-rest`
or
`web.interface.url=http://irods-cloud.mydomain.com/irods-rest`
or
`web.interface.url=irods-cloud.mydomain.com/irods-rest`
and if I'm using SSL in front via apache, should I be doing;
`web.interface.url=https://irods-cloud.mydomain.com/irods-rest`

I know there are a lot of possible permutations, but its not clear to me if the URL is from the viewpoint of the client or the server process. Apologies if this is an obvious issue if one knows Tomcat!

**Comment by kript** [comment]
Actually, looking at the documentation for `jargon-beans.xml`, before it, it appears that the web interface might actually be referring to, say, irods-cloud-browser, rather than the internal RESt service?

Also, if one configures `/etc/irods-ext/irods-rest.properties` does one also need to configure `src/main/resources/jargon-beans.xml`? I was assuming not, but..

cheers

John

**Comment by michael-conway** [comment]
There is a convention of /etc/irods-ext for .properties files and 
configuration for various components.

The REST properties are distinct from the configuration for the cloud 
browser.  REST and the cloud browser, as well as webdav will look in 
/etc/irods-ext for these configs.  All three of those components are 
pre-wired to integrate properties settings there on startup, so altering 
the spring configuration or grails configuration is not necessary.


For grails, here is a template for the configuration
https://github.com/DICE-UNC/irods-cloud-browser/blob/master/irods-cloud-backend/misc/irods-cloud-backend-config.groovy

Currently the primary configuration consideration for cloud browser is 
to prefill the host/port, etc for iRODS login.  As we add more custom 
plugins that will be expanded.

MC

**Comment by kript** [comment]
I'm putting this on the same server as the irods cloud browser, the previous config looked in `/etc/irods-cloud-backend-config.groovy` rather than `/etc/irods-ext/irods-cloud-backend-config.groovy` is that a change for that application?

**Comment by michael-conway** [comment]
That is correct, it goes under /etc/irods-ext

As we added REST and WebDav, it made sense to consolidate under one 
standard location.  FWIW the grails configuration shows how it is picked 
up from a series of locations...so for grails there are several places 
it can look!

https://github.com/DICE-UNC/irods-cloud-browser/blob/master/irods-cloud-backend/grails-app/conf/Config.groovy#L6

MC

**Comment by michael-conway** [comment]
PS that web interface url is currently not used so I'm just going to yank it from the example.  We'll be reconsidering structuring this in the next revs of cloud browser and REST, the idea is to formalize the concept of an http referable home for irods objects.
