### ISSUE TITLE
Issues deploying and running on TomEE

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-rest#7]
Servlet execution threw an exception deploying/running on TomcatEE

There have been a string of issues with Leesa Brieger running this

exception

javax.servlet.ServletException: Servlet execution threw an exception
    org.irods.jargon.rest.auth.BasicAuthFilter.doFilter(BasicAuthFilter.java:116)
    org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)

root cause

java.lang.NoSuchMethodError: org.jboss.resteasy.specimpl.BuiltResponse.getHeaders()Ljavax/ws/rs/core/MultivaluedMap;
    org.jboss.resteasy.core.ServerResponseWriter.setDefaultContentType(ServerResponseWriter.java:186)
    org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:46)
    org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:427)
    org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:376)
    org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
    org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
    org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
    org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    org.irods.jargon.rest.auth.BasicAuthFilter.doFilter(BasicAuthFilter.java:116)
    org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)

This still looks like an issue of resteasy deployment in TomEE...

**Comment by Kajvdh** [comment]
@michael-conway How did you manage to solve this issue? I have the same problem
