### ISSUE TITLE
Problem authentificating from irods-rest

### ISSUE THREAD

**Issue by RubenGarcia** [DICE-UNC/irods-rest#71]
We have followed the instructions on 
https://github.com/DICE-UNC/irods-rest/blob/master/docs/iRODS_REST_API_Documentation.asciidoc
but we are getting a 
401 error 
at the very end of section 3
We tested both 
irods 4.1.10 and 4.2.5 
with irods-rest latest master
with the same problem in both.

Are there any extra caveats not mentioned in
https://github.com/DICE-UNC/irods-rest/blob/master/docs/iRODS_REST_API_Documentation.asciidoc
?

**Comment by RubenGarcia** [comment]
The issue is the same as shown on 
https://github.com/DICE-UNC/jargon/issues/223

[main] ERROR org.irods.jargon.core.connection.SslConnectionUtilities - ssl exception in handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

I used 
                <beans:property name="sslNegotiationPolicy" value="CS_NEG_REFUSE" />
                <beans:property name="computeChecksum" value="false" />
and disabled ssl on the irods server on  /etc/irods/server_config.json by adding
"irods_client_server_negotiation": "none"

After these steps, I could authentificate. The solution is not optimal, so please have a look at ssl negotiation and investigate why irods is closing the connection.

Thank you

**Comment by michael-conway** [comment]
Hi Ruben are you using a self-signed SSL certificate on the IRODS side?

**Comment by RubenGarcia** [comment]
We are using the standard guide on 
https://docs.irods.org/4.2.5/getting_started/installation/
which does not mention certificates.
If I am using self-signed SSL certificates, they have been created by IRODS without my knowledge.

If self-signed certificates are a problem, this should probably be documented at
https://github.com/DICE-UNC/irods-rest/blob/master/docs/iRODS_REST_API_Documentation.asciidoc

**Comment by trel** [comment]
iRODS does not create or maintain certificates.

**Comment by michael-conway** [comment]
If a self signed ssl cert was added in the PAM setup, it needs to be in the
JVM keystore

https://github.com/DICE-UNC/jargon/wiki/Setting-up-PAM

If running via Docker there is a facility to have that cert imported by
providing it as a volume mount in the docker run command

https://github.com/DICE-UNC/irods-rest/blob/master/Docker.md

See of those help address things otherwise pull requests are always
welcome!  This is an old API that will sometime be updated...

**Comment by RubenGarcia** [comment]
I am using standard user/password authentification, not PAM. However, irods has a configuration file
/etc/irods/server_config.json
with an optional configuration option irods_client_server_negotiation which by default requests SSL. Since SSL requires a certificate, either irods or a supporting library is creating a certificate behind the scenes. And this certificate seems not to be liked by irods-rest.

**Comment by RubenGarcia** [comment]
From
https://docs.irods.org/master/plugins/pluggable_authentication/#server-ssl-setup
I see that irods uses the certificats from
"irods_ssl_certificate_chain_file": "/etc/irods/chain.pem",
"irods_ssl_certificate_key_file": "/etc/irods/server.key",
"irods_ssl_dh_params_file": "/etc/irods/dhparams.pem",
if they have been configured; so I undertand that otherwise, a self-signed certificate will be created. 
I'll test the use of proper certificates and request a clarification on
https://github.com/DICE-UNC/irods-rest/blob/master/docs/iRODS_REST_API_Documentation.asciidoc
regarding this issue on the irods side.
Thank you for the pointers.

**Comment by michael-conway** [comment]
You can set the server in core.re to cs_neg_refuse and this should take
care of it. Irods won't create a cert for you.

**Comment by RubenGarcia** [comment]
I see. So irods itself is closing the connection because it does not have a certificate, right? And my supposition that irods-rest was not liking the certificate is wrong.

**Comment by michael-conway** [comment]
I think this is the case. Setting CS_NEG_REFUSE in the rules causes iRODS
to cease negotiating SSL.  What is true is that, when implementing a
self-signed SSL cert, Java itself requires that public key to be present in
the keystore, so it's an issue with Java security (and probably rightly so,
from an 'enterprise' perspective').

A handy thing is that the Docker image does provide the ability to add a
volume mount of the public SSL key and it will automatically provision the
Docker image with that self-signed cert on demand.

**Comment by RubenGarcia** [comment]
I confirm that the issue is resolved once the certificates are imported into java via

keytool -import -trustcacerts -keystore /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts -storepass changeit -alias Root -import -file chain.pem

Closing issue.
