### ISSUE TITLE
Add Ticket support

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-rest#9]
Add support for Tickets, might need to include 'ls' support in Jargon

**Comment by naevtamarkus** [comment]
:+1: to this!
Any work being done on this API? I see last milestone was modified one year ago
Thanks!

**Comment by michael-conway** [comment]
Yes, we are actively working on the API.  Justin at the consortium just
added
query support.

We've not done tickets yet, we are spread very thin on the API side.

**Comment by michael-conway** [comment]
Specification

##Add filter

 Add a new servlet filter like this https://github.com/DICE-UNC/irods-rest/blob/master/src/main/java/org/irods/jargon/rest/auth/BasicAuthFilter.java

Note that the filter is wired in with https://github.com/DICE-UNC/irods-rest/blob/master/src/main/resources/jargon-beans.xml  and the delgating filter proxy, so we want to order this before the Basic Auth filter

##Filter uses ticket service to initialize the session with the provided ticket.

Use the TicketClientSupport class to initialize the ticket in the iRODS session

https://github.com/DICE-UNC/jargon/blob/master/jargon-ticket/src/main/java/org/irods/jargon/ticket/TicketClientSupport.java#L53-L69

Note that we'll need a standard location in the URL for the ticket token, so we can just standardize on &ticket=ticketstringhere

## Wire ticket awareness into BasicAuthFilter

the basic auth filter will need to understand that a ticket is in the URL, and if so, and no basic auth tokens are provided, instead of generating a 401 not authorized, will need to introduce a guest IRODSAccount

## Functional tests

We'll need to augment the unit tests with analogous ticket based tests of each operation.  I remain somewhat concerned that ticket support within iRODS may run into snags in some detailed operations.

**Comment by michael-conway** [comment]
use branch https://github.com/DICE-UNC/irods-rest/tree/issue9

**Comment by JustinKyleJames** [comment]
Mike, can you explain what you mean by introducing a guest account?

**Comment by michael-conway** [comment]
sure..
the ticket filter, or the basic auth filter, needs to set an IRODSAccount
in the request attributes as they are picked up by the REST services.  If
they are using a ticket with no real credentials,we need to make sure we've
provided an iRODSAccount in the request.

You can create an anonymous iRODS account for this...

/**
     * Create an <code>IRODSAccount</code> suitable for anonymous access.
     *
     * @param host
     *            <code>String</code> with the DNS name of the iRODS host
     * @param port
     *            <code>int</code> with the iRODS port number (typically
1247)
     * @param homeDirectory
     *            <code>String</code> with optional value for the starting
home
     *            directory, this can be used to set initial views, etc by
other
     *            code
     * @param zone
     *            <code>String</code> with the iRODS zone
     * @param defaultStorageResource
     *            <code>String</code> with optional value for the default
     *            storage resource. Note that iRODS may have defaults set by
     *            policy. In cases where no default policy exists, and none
is
     *            specified here, an error can occur.
     * @return <code>IRODSAccount</code> suitable for anonymous access
     * @throws JargonException
     */
    public static IRODSAccount instanceForAnonymous(final String host,
            final int port, final String homeDirectory, final String zone,
            final String defaultStorageResource) throws JargonException {
        return instance(host, port, PUBLIC_USERNAME, "", "", zone,
                defaultStorageResource);
    }



In IRODSAccount.  We can look at this tomorrow morning!  It's so the
eventual service implementation doesn't have a 'null' irods account.

MC

**Comment by michael-conway** [comment]
ticket represents initial dev work, closing and moving any remaining issues to individual tickets
